apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
stringData:
  github_token: GITHUB_TOKEN_PLACEHOLDER
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: actions-runner-controller-helm
  namespace: actions-runner-system
data:
  values.yaml: |
    authSecret:
      create: false
      name: controller-manager
    
    # Scale down to 0 when not needed
    replicaCount: 1
    
    # Resources for the controller
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-actions-runner-controller
  namespace: actions-runner-system
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: actions-runner-controller-installer
      containers:
      - name: helm
        image: alpine/helm:latest
        command:
        - sh
        - -c
        - |
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          helm repo update
          helm upgrade --install actions-runner-controller \
            actions-runner-controller/actions-runner-controller \
            --namespace actions-runner-system \
            --values /config/values.yaml \
            --wait
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: actions-runner-controller-helm
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller-installer
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner-controller-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: actions-runner-controller-installer
  namespace: actions-runner-system
