apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create namespace before apps
spec:
  project: default
  source:
    repoURL: https://github.com/one-t/proxmox-argo-helm
    targetRevision: main
    path: isolated-namespace
    helm:
      values: |
        namespaceName: demo-apps
        
        namespaceLabels:
          environment: demo
          managed-by: argocd
        
        resourceQuota:
          enabled: true
          hard:
            pods: "30"
            requests.cpu: "2"
            requests.memory: "4Gi"
            limits.cpu: "4"
            limits.memory: "8Gi"
            persistentvolumeclaims: "5"
            services: "15"
            configmaps: "30"
            secrets: "30"
        
        networkPolicy:
          enabled: true
          allowDNS: true
          allowKubeSystem: true
          allowIngressController: true
          allowExternalEgress: true
          # Demo apps don't need access to other namespaces
          allowEgressTo: []
  
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
