apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-apps
  namespace: argocd
spec:
  description: Demo Apps Project
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/one-t/proxmox-argo.git'
  - 'https://github.com/one-t/proxmox-argo-helm.git'
  - '*'  # Allow any repo for demos
  
  # Destinations
  destinations:
  - namespace: demo-apps
    server: https://kubernetes.default.svc
  
  # Cluster resource allow list
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  
  # Namespace resource allow list
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # Orphaned resources
  orphanedResources:
    warn: true
